name: Deploy on EC2 staging server

# Trigger Deployment only on push to main | master branch
on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Debug labels
        run: echo 'Labels ${{ toJson(github.event.pull_request.labels) }}'
        continue-on-error: true

      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.STAGING_TARGET_DIR }}

      # - name: Start or Restart Project
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST_DNS }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     script: |
      #       cd ${{ secrets.STAGING_TARGET_DIR }}
      #       . .venv/bin/activate
      #       pm2 restart all
